# Generated by Django 4.2.5 on 2023-10-05 07:35

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name & family')),
                ('email', models.EmailField(max_length=100)),
                ('number', contact.models.IntegerRangeField(default=1, verbose_name='number of person')),
                ('text', models.TextField()),
            ],
        ),
    ]
