# Generated by Django 4.2.5 on 2023-09-16 09:00

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='pup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=food.models.IntegerRangeField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name='زمان پخت'),
        ),
    ]
