# Generated by Django 4.2.5 on 2023-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name & family')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('number', models.IntegerField(verbose_name='number of person')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
