# Generated by Django 4.2.5 on 2023-09-23 06:51

import Reservation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=Reservation.models.IntegerRangeField(default=1, verbose_name='number of person'),
        ),
    ]
